Footer ready
ruslan-astratov/lesson-pull-request pull request #1
Opened 2020-08-10 15:35 UTC by ruslan-astratov

Сверстал подвал.

2020-08-11 10:08 UTC, nobleworkshop requested changes
Хорошо, но есть один нюанс.

1) Зайдите в раздел "Files changed" и вы увидите сколько строчек git воспринимает как новые. А все из-за того что были изменены отступы. Не стоит так поступать. Нужно оставлять отступы как в проекте, и добавлять/вносить изменения только там где надо. 

![image](https://user-images.githubusercontent.com/12967597/89885323-90ac1300-dbd3-11ea-8a1f-feca01c64b8b.png)

2) По футеру - давайте поменяем его фон на черный.

Когда внесете правки - напишите пожалуйста также ответ в уроке на обучающей платформе GetCourse.

2020-08-11 10:54 UTC, ruslan-astratov reviewed
Поменял цвет футера

2020-08-11 10:57 UTC, nobleworkshop requested changes
Остались отступы: 
![image](https://user-images.githubusercontent.com/12967597/89889579-86d9de00-dbda-11ea-85d4-070b834a403e.png)

2020-08-11 11:07 UTC, ruslan-astratov reviewed
@nobleworkshop 
Переделал отступы

2020-08-13 12:42 UTC, merged

2020-08-13 16:16 UTC, nobleworkshop commented
Аппрува не было, а мерж уже прошел. Не порядок) 
В командной работе так не надо делать.

Здесь - ок, ставлю зачет. И с отступами надо будет аккуратно работать.